### PR TITLE
fixed encryption of incoming stock data

### PR DESCRIPTION
**Pull request by sedwards2000**
The incoming data is now encrypted, used a fix from a different yf package in a new request: https://github.com/ranaroussi/yfinance/pull/1253/commits/8e5f0984af347afda6be74b27a989422e49a975b.

Now decrypts the data after getting it

### CODE REVIEW

**Comment by lrauhockey** [comment]
looks good who can approve?

**Comment by divyankm** [comment]
@JECSand Pls approve Merge request

**Comment by Vince050** [comment]
I get an error when adding/removing these lines:

from yahoofinancials import YahooFinancials
  File "C:\Users\Vince\AppData\Local\Programs\Python\Python310\lib\site-packages\yahoofinancials\__init__.py", line 173
    elif tech_type != '' and statement_type != 'history':
    ^^^^
IndentationError: expected an indented block after 'if' statement on line 172

**Comment by JECSand** [comment]
@divyankm Just approved it, thank you for fixing this.

**Pull request merged**
