### PR TITLE
Fix upstream

### LINKED ISSUE #57: get_current_price() returning none for everything
stock = YahooFInancials('ABB.BO')
cmp = stock.get_current_price()
cmp

returns None

Also happening with atleast volumes and market cap fields as well.

### LINKED ISSUE #71: Unknown error - AttributeError: 'NoneType' object has no attribute 'group
I just installed this with:
$ pip install yahoofinancials

I added a very simple script:
from yahoofinancials import YahooFinancials
yahoo_financials = YahooFinancials('AAPL')
print(yahoo_financials.get_market_cap())

And I got the following error:
  File "Main.py", line 9, in parse
    print(yahoo_financials.get_market_cap())
  File "/Library/Python/2.7/site-packages/yahoofinancials/__init__.py", line 737, in get_market_cap
    return self._stock_price_data('marketCap')
  File "/Library/Python/2.7/site-packages/yahoofinancials/__init__.py", line 649, in _stock_price_data
    if self.get_stock_price_data()[self.ticker] is None:
  File "/Library/Python/2.7/site-packages/yahoofinancials/__init__.py", line 603, in get_stock_price_data
    return self.get_clean_data(self.get_stock_tech_data('price'), 'price')
  File "/Library/Python/2.7/site-packages/yahoofinancials/__init__.py", line 491, in get_stock_tech_data
    return self.get_stock_data(tech_type=tech_type)
  File "/Library/Python/2.7/site-packages/yahoofinancials/__init__.py", line 473, in get_stock_data
    dict_ent = self._create_dict_ent(self.ticker, statement_type, tech_type, report_name, hist_obj)
  File "/Library/Python/2.7/site-packages/yahoofinancials/__init__.py", line 406, in _create_dict_ent
    re_data = self._scrape_data(YAHOO_URL, tech_type, statement_type)
  File "/Library/Python/2.7/site-packages/yahoofinancials/__init__.py", line 153, in _scrape_data
    self._cache[url] = loads(re.search("root.App.main\s+=\s+(\{.*\})", script).group(1))
AttributeError: 'NoneType' object has no attribute 'group

### PR DESCRIPTION
**Pull request by sylvandb**
accumulated fixes, see commit comments

includes pr #61 which:
Fixes #57
Maybe Fixes? #58
Maybe Fixes? #59

Adds:
Fixes 'adjusted-close' aspect of #64
Fixes #71

### CODE REVIEW

**Comment by HyperionSounds** [comment]
how can we merge this with the master so it will pip install? I am running my platform across multiple environments

**Comment by cliffchew84** [comment]
Thanks. This helped me fixed my issue. I wasn't able to figure out how to merge this with my pip install, and I just modified the code based on the code changes made here.

**Comment by juanmf** [comment]
> Thanks. This helped me fixed my issue. I wasn't able to figure out how to merge this with my pip install, and I just modified the code based on the code changes made here.

it'd be cool to have pip installing this, or at least having this branch installed without manually modifying the code. any link on how to do it?

**Comment by krema** [comment]
@sylvandb Can you please make a separate pull request for the bs4 change? There are so many "maybe" fixes in this pull request that it will probably never be merged. I am happy to help if you want me to do it.

@ThomasGsp Or can we merge it already?

@juanmf `pip install -e git+https://github.com/sylvandb/yahoofinancials.git#egg=yahoofinancials`

**Comment by sylvandb** [comment]
@krema @juanmf I'm not sure that pip command line will do what you desire. I do not use pip like that, but that command appears like it will take my master branch which has diverged in several ways from the upstream version in this repo. I have tried for only improvements, but it may not work outside of my specific use case. I use only a small portion of the functionality...

The previous PR should be merged first or @JECSand could cherry-pick individual commits as desired.

Of course please feel free to take individual commits or even create new commits from my work.

**Comment by krema** [comment]
@sylvandb Thank you for your efforts but this project appears to be dead. I don't want to spend any more time fixing problems in this project. There are too many unresolved issues. The last release was 17 month ago. I switched to another project (yahooquery) that is active and even has yahoo premium support.

**Comment by JECSand** [comment]
Hey all,

I’ve been in the process of starting my own business. I had no idea this would become so popular. Haven’t checked on this in awhile. I made the merges into the base branch just now. I’ll be on here paying more attention. 

Really apologize for any inconveniences.

**Pull request merged**
