### PR TITLE
Add financial data

### PR DESCRIPTION
**Pull request by flipdazed**
Current vital statistics are missing like total debt.

This resolves that problem

### CODE REVIEW

**Comment by flipdazed** [comment]
feel free to edit as you see fit... I think this would just require a README adjustment

**Comment by flipdazed** [comment]
added docs as well

**Comment by jjphung** [comment]
Unit tests?

**Comment by dalder1** [comment]
Could you explain how to implement this?

**Review by dalder1 — APPROVED** [review]

**Comment by dalder1** [comment]
let's get this moving asap, adds in much needed functionality

**Pull request merged**
